import type { HttpLoadProfile, HttpLoadTestConfig } from "./http-types";

const DEFAULT_WORKER_COUNT = 2;
const DEFAULT_POOL_SIZE = 4;
const DEFAULT_OPERATION_TIMEOUT_MS = 30_000;
const DEFAULT_WORKER_READY_TIMEOUT_MS = 60_000;
const DEFAULT_RUN_TIMEOUT_MS = 7_200_000;
const DEFAULT_ACCOUNT_COUNT = 20;
const DEFAULT_ACTIVE_USER_COUNT = 20;
const DEFAULT_OPERATIONS_PER_USER = 5;
const DEFAULT_HOT_ACCOUNT_COUNT = 2;
const DEFAULT_HOT_TRAFFIC_PERCENT = 75;
const DEFAULT_HISTORY_EVENTS_PER_ACCOUNT = 20;
const DEFAULT_SEED_BATCH_SIZE = 1_000;
const DEFAULT_REQUEST_COUNT = 100;
const DEFAULT_DURATION_SECONDS = 0;
const DEFAULT_READ_PERCENT = 40;
const DEFAULT_CONCURRENCY = 16;
const DEFAULT_MAX_RETRIES = 8;
const DEFAULT_CAPACITY_START_RPS = 100;
const DEFAULT_CAPACITY_STEP_RPS = 100;
const DEFAULT_CAPACITY_MAX_RPS = 2_000;
const DEFAULT_CAPACITY_STAGE_SECONDS = 30;
const DEFAULT_SLO_READ_P95_MS = 250;
const DEFAULT_SLO_DEPOSIT_P95_MS = 500;
const DEFAULT_SLO_ERROR_RATE_PERCENT = 0.1;
const DEFAULT_SNAPSHOT_BENCHMARK_REQUESTS = 1_000;
const DEFAULT_SNAPSHOT_BENCHMARK_HISTORY = 10_000;
const DEFAULT_SEED = 1;
const NO_SNAPSHOT_BENCHMARK_REQUESTS = 0;
const DAILY_WORKER_COUNT = 3;
const DAILY_POOL_SIZE = 10;
const DAILY_ACCOUNT_COUNT = 100_000;
const DAILY_ACTIVE_USER_COUNT = 100_000;
const DAILY_OPERATIONS_PER_USER = 10;
const NO_HOT_ACCOUNTS = 0;
const NO_HOT_TRAFFIC = 0;
const DAILY_HISTORY_EVENTS = 60;
const DAILY_REQUEST_COUNT = 1_000_000;
const DAILY_DURATION_SECONDS = 3_600;
const DAILY_READ_PERCENT = 70;
const DAILY_CONCURRENCY = 256;
const DAILY_MAX_RETRIES = 20;
const CAPACITY_WORKER_COUNT = 3;
const CAPACITY_POOL_SIZE = 10;
const CAPACITY_ACCOUNT_COUNT = 20_000;
const CAPACITY_ACTIVE_USER_COUNT = 20_000;
const CAPACITY_OPERATIONS_PER_USER = 32;
const CAPACITY_HOT_ACCOUNT_COUNT = 500;
const CAPACITY_HOT_TRAFFIC_PERCENT = 10;
const CAPACITY_HISTORY_EVENTS = 60;
const CAPACITY_REQUEST_COUNT = 630_000;
const CAPACITY_DURATION_SECONDS = 600;
const CAPACITY_READ_PERCENT = 70;
const CAPACITY_CONCURRENCY = 1_024;
const CAPACITY_MAX_RETRIES = 20;

export const DEFAULT_HTTP_LOAD_TEST_CONFIG: HttpLoadTestConfig = {
  profile: "custom",
  workerCount: DEFAULT_WORKER_COUNT,
  poolSize: DEFAULT_POOL_SIZE,
  operationTimeoutMs: DEFAULT_OPERATION_TIMEOUT_MS,
  workerReadyTimeoutMs: DEFAULT_WORKER_READY_TIMEOUT_MS,
  runTimeoutMs: DEFAULT_RUN_TIMEOUT_MS,
  accountCount: DEFAULT_ACCOUNT_COUNT,
  activeUserCount: DEFAULT_ACTIVE_USER_COUNT,
  operationsPerUser: DEFAULT_OPERATIONS_PER_USER,
  hotAccountCount: DEFAULT_HOT_ACCOUNT_COUNT,
  hotTrafficPercent: DEFAULT_HOT_TRAFFIC_PERCENT,
  historyEventsPerAccount: DEFAULT_HISTORY_EVENTS_PER_ACCOUNT,
  seedBatchSize: DEFAULT_SEED_BATCH_SIZE,
  requestCount: DEFAULT_REQUEST_COUNT,
  durationSeconds: DEFAULT_DURATION_SECONDS,
  readPercent: DEFAULT_READ_PERCENT,
  concurrency: DEFAULT_CONCURRENCY,
  maxRetries: DEFAULT_MAX_RETRIES,
  capacityStartRequestsPerSecond: DEFAULT_CAPACITY_START_RPS,
  capacityStepRequestsPerSecond: DEFAULT_CAPACITY_STEP_RPS,
  capacityMaxRequestsPerSecond: DEFAULT_CAPACITY_MAX_RPS,
  capacityStageSeconds: DEFAULT_CAPACITY_STAGE_SECONDS,
  enforceSlos: false,
  sloReadP95Ms: DEFAULT_SLO_READ_P95_MS,
  sloDepositP95Ms: DEFAULT_SLO_DEPOSIT_P95_MS,
  sloErrorRatePercent: DEFAULT_SLO_ERROR_RATE_PERCENT,
  snapshotBenchmarkRequests: DEFAULT_SNAPSHOT_BENCHMARK_REQUESTS,
  snapshotBenchmarkHistoryEventsPerAccount: DEFAULT_SNAPSHOT_BENCHMARK_HISTORY,
  seed: DEFAULT_SEED,
  verbose: false,
};

export const PROFILE_DEFAULTS: Record<HttpLoadProfile, HttpLoadTestConfig> = {
  custom: DEFAULT_HTTP_LOAD_TEST_CONFIG,
  daily: {
    ...DEFAULT_HTTP_LOAD_TEST_CONFIG,
    profile: "daily",
    workerCount: DAILY_WORKER_COUNT,
    poolSize: DAILY_POOL_SIZE,
    accountCount: DAILY_ACCOUNT_COUNT,
    activeUserCount: DAILY_ACTIVE_USER_COUNT,
    operationsPerUser: DAILY_OPERATIONS_PER_USER,
    hotAccountCount: NO_HOT_ACCOUNTS,
    hotTrafficPercent: NO_HOT_TRAFFIC,
    historyEventsPerAccount: DAILY_HISTORY_EVENTS,
    requestCount: DAILY_REQUEST_COUNT,
    durationSeconds: DAILY_DURATION_SECONDS,
    readPercent: DAILY_READ_PERCENT,
    concurrency: DAILY_CONCURRENCY,
    maxRetries: DAILY_MAX_RETRIES,
    enforceSlos: true,
    snapshotBenchmarkRequests: NO_SNAPSHOT_BENCHMARK_REQUESTS,
  },
  capacity: {
    ...DEFAULT_HTTP_LOAD_TEST_CONFIG,
    profile: "capacity",
    workerCount: CAPACITY_WORKER_COUNT,
    poolSize: CAPACITY_POOL_SIZE,
    accountCount: CAPACITY_ACCOUNT_COUNT,
    activeUserCount: CAPACITY_ACTIVE_USER_COUNT,
    operationsPerUser: CAPACITY_OPERATIONS_PER_USER,
    hotAccountCount: CAPACITY_HOT_ACCOUNT_COUNT,
    hotTrafficPercent: CAPACITY_HOT_TRAFFIC_PERCENT,
    historyEventsPerAccount: CAPACITY_HISTORY_EVENTS,
    requestCount: CAPACITY_REQUEST_COUNT,
    durationSeconds: CAPACITY_DURATION_SECONDS,
    readPercent: CAPACITY_READ_PERCENT,
    concurrency: CAPACITY_CONCURRENCY,
    maxRetries: CAPACITY_MAX_RETRIES,
    enforceSlos: true,
    snapshotBenchmarkRequests: NO_SNAPSHOT_BENCHMARK_REQUESTS,
  },
};
